version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spothero
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spothero
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db